#!/bin/bash

HOST=$1

STATUS=$(curl -f -s http://$HOST/api/status)
if [ $? -ne 0 ];
then
    echo "CRITICAL - failed to contact lovebeat server on $HOST"
    exit 2
fi

NUM_OK=$(echo "$STATUS" | awk '/num_ok/ { print $2 }')
NUM_ERROR=$(echo "$STATUS" | awk '/num_error/ { print $2 }')

LINE="ok: ${NUM_OK}, errors: ${NUM_ERROR}"
if [ "$NUM_ERROR" != "0" ];
then
    echo "CRITICAL - $LINE"
    exit 2
fi

echo "OK - $LINE"
exit 0
